# Generated by Django 2.2.7 on 2019-11-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='learning_semester',
            field=models.CharField(choices=[('Jan-Apr', 'Jan - Apr'), ('May-Aug', 'May - Aug'), ('Sept-Dec', 'Sept - Dec')], max_length=15, verbose_name='Semester Joined'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='learning_year',
            field=models.IntegerField(default=2019, verbose_name='Year Joined'),
        ),
    ]
