# Generated by Django 3.0.2 on 2020-01-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0002_auto_20191127_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='learning_year',
            field=models.IntegerField(default=2020, verbose_name='Year Joined'),
        ),
    ]
