# Generated by Django 2.2.7 on 2019-11-26 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.IntegerField(unique=True)),
                ('category', models.CharField(choices=[('Finance', 'Finance'), ('HOD', 'Head of Department'), ('Lecturer', 'Lecturer'), ('Nurse', 'Nurse')], max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
