# Generated by Django 2.2.7 on 2019-11-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20191126_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
