# Generated by Django 2.2.7 on 2019-11-26 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='national_id',
        ),
    ]
