# Generated by Django 2.2.7 on 2019-11-26 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year_joined', models.IntegerField(default=2019)),
                ('semester_joined', models.CharField(choices=[('Jan-Apr', 'Jan - Apr'), ('May-Aug', 'May - Aug'), ('Sept-Dec', 'Sept - Dec')], max_length=15)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
