# Generated by Django 2.2.7 on 2019-11-27 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_auto_20191126_0241'),
        ('course_registration', '0002_auto_20191127_0506'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2019)),
                ('semester', models.CharField(choices=[('Jan-Apr', 'Jan - Apr'), ('May-Aug', 'May - Aug'), ('Sept-Dec', 'Sept - Dec')], max_length=15)),
                ('enrolled_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_registration.CourseRegistration')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
    ]
