# Generated by Django 2.2.7 on 2019-11-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_fee_payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentfeepayment',
            old_name='student_id',
            new_name='student',
        ),
    ]
